title: CuteLang Documentation
description: The most kawaii functional programming language!
theme: minima
markdown: kramdown
logo: https://em-content.zobj.net/source/twitter/408/sparkling-heart_1f496.png